version: "3.8"
services:
  db:
    container_name: "db"
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - custom
  redis:
    container_name: "redis"
    image: redis:7.0-alpine
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - custom
volumes:
  postgres_db:
networks:
  custom:
    driver: bridge
